---
- name: make an instance
  user: fdavis
  hosts: local
  connection: paramiko
  gather_facts: False

  vars_files:
  - vars/main.yml

  tasks:
    - include: tasks/setup.yml
      with_items: ${servers}
