---
- command: iptables -I INPUT 1 -p udp --dport 123 -j ACCEPT

- copy: src=files/ntp.conf dest=/etc/ntp.conf owner=root group=root mode=0600 backup=yes

- service: name=ntpd state=started enabled=yes
